config/routes.rb
Rails.application.routes.draw do
    
    resources :users
    resources :raiders
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'application#hello'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/raider.rb
class Raider < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    protect_from_forgery with: :exception

    def hello
        render html: "hello world!"
    end

end

app/controllers/raiders_controller.rb
class RaidersController < ApplicationController
  before_action :set_raider, only: [:show, :edit, :update, :destroy]

  # GET /raiders
  # GET /raiders.json
  def index
    @raiders = Raider.all
  end

  # GET /raiders/1
  # GET /raiders/1.json
  def show
  end

  # GET /raiders/new
  def new
    @raider = Raider.new
  end

  # GET /raiders/1/edit
  def edit
  end

  # POST /raiders
  # POST /raiders.json
  def create
    @raider = Raider.new(raider_params)

    respond_to do |format|
      if @raider.save
        format.html { redirect_to @raider, notice: 'Raider was successfully created.' }
        format.json { render :show, status: :created, location: @raider }
      else
        format.html { render :new }
        format.json { render json: @raider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raiders/1
  # PATCH/PUT /raiders/1.json
  def update
    respond_to do |format|
      if @raider.update(raider_params)
        format.html { redirect_to @raider, notice: 'Raider was successfully updated.' }
        format.json { render :show, status: :ok, location: @raider }
      else
        format.html { render :edit }
        format.json { render json: @raider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raiders/1
  # DELETE /raiders/1.json
  def destroy
    @raider.destroy
    respond_to do |format|
      format.html { redirect_to raiders_url, notice: 'Raider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raider
      @raider = Raider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raider_params
      params.require(:raider).permit(:name, :wowclass, :role, :battletag, :rank)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/raiders_helper.rb
module RaidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raidmanager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/raiders/_form.html.erb
<%= form_for(raider) do |f| %>
  <% if raider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(raider.errors.count, "error") %> prohibited this raider from being saved:</h2>

      <ul>
      <% raider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :wowclass %>
    <%= f.text_field :wowclass %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>

  <div class="field">
    <%= f.label :battletag %>
    <%= f.text_field :battletag %>
  </div>

  <div class="field">
    <%= f.label :rank %>
    <%= f.text_field :rank %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/raiders/edit.html.erb
<h1>Editing Raider</h1>

<%= render 'form', raider: @raider %>

<%= link_to 'Show', @raider %> |
<%= link_to 'Back', raiders_path %>

app/views/raiders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Raiders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Wowclass</th>
      <th>Role</th>
      <th>Battletag</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @raiders.each do |raider| %>
      <tr>
        <td><%= raider.name %></td>
        <td><%= raider.wowclass %></td>
        <td><%= raider.role %></td>
        <td><%= raider.battletag %></td>
        <td><%= raider.rank %></td>
        <td><%= link_to 'Show', raider %></td>
        <td><%= link_to 'Edit', edit_raider_path(raider) %></td>
        <td><%= link_to 'Destroy', raider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Raider', new_raider_path %>

app/views/raiders/new.html.erb
<h1>New Raider</h1>

<%= render 'form', raider: @raider %>

<%= link_to 'Back', raiders_path %>

app/views/raiders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @raider.name %>
</p>

<p>
  <strong>Wowclass:</strong>
  <%= @raider.wowclass %>
</p>

<p>
  <strong>Role:</strong>
  <%= @raider.role %>
</p>

<p>
  <strong>Battletag:</strong>
  <%= @raider.battletag %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @raider.rank %>
</p>

<%= link_to 'Edit', edit_raider_path(@raider) %> |
<%= link_to 'Back', raiders_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>